# Generated by Django 4.0.5 on 2022-08-05 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_gender_user_device_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
