# Generated by Django 4.0.5 on 2022-08-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
