# Generated by Django 4.0.5 on 2022-08-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_address_user_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='users',
            new_name='customers',
        ),
    ]
