# Generated by Django 4.0.5 on 2022-08-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customer_user'),
        ('orders', '0005_remove_wishlist_user_wishlist_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='customers',
            field=models.ManyToManyField(blank=True, to='users.customer'),
        ),
    ]
