# Generated by Django 4.0.5 on 2022-08-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_coupon_customers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-ordered_date']},
        ),
    ]
